trigger:
- master

pool: 'default'


stages:
  - stage: 
    displayName: 'Deploy'
    jobs:
      - job:
        displayName: 'Build & Deploy'
        steps:
          - task: Bash@3
            displayName: "Build"
            inputs:
              targetType: 'inline'
              script: |
                export NVM_DIR="$HOME/.nvm"
                [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
                [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
                npm install
                npm run build
          - task: Bash@3
            displayName: "Deploy"
            inputs:
              targetType: 'inline'
              script: |
                echo 'Hello World'